/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.iesb.meuprograma.apresentacao;

/**
 *
 * @author Carolina
 */
public class JDialogCadastroCategorias extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadastroCategorias
     */
    public JDialogCadastroCategorias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro de Categorias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Outras Receitas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Despesas Administrativas e Comerciais");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Entradas Operacionais");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 20));

        jButton1.setText("Nova Categoria ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jButton2.setText("Criar Sub-Categoria");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jButton3.setText("Editar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ajuste de Caixa");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jRadioButton3.setText("Devolução de Adiantamentos");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Vendas");
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Receebimentos de Cotas Condomínios - Residencial");
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Recebimentos de Cotas Condomínios - Comercial ");
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Recebimentos de taxas para uso do Salão de Festas");
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Taxa de reposição de bem da área comum");
        jPanel1.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("Taxa de reparo de bem da área comom");
        jPanel1.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("Recebimento de taxas diversas ");
        jPanel1.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("Fundo de reserva");
        jPanel1.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText("Recebimento Gás");
        jPanel1.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setText("Recebimento Luz");
        jPanel1.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setText("Recebimento Água/Esgoto");
        jPanel1.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("Recebimento Seguros");
        jPanel1.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setText("Outros Rateios");
        jPanel1.add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setText("Multas por atraso");
        jPanel1.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setText("Rendimentos Financeiros");
        jPanel1.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Receitas de Financeiras");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, 20));

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setText("Despesa com Água/Esgoto");
        jPanel1.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        buttonGroup1.add(jRadioButton20);
        jRadioButton20.setText("Despesa com energia elétria");
        jPanel1.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setText("Despesa com Assessoria");
        jPanel1.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setText("Despesa com Cartório");
        jPanel1.add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, -1, -1));

        buttonGroup1.add(jRadioButton23);
        jRadioButton23.setText("Despesa com Combustiveis");
        jPanel1.add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, -1, -1));

        buttonGroup1.add(jRadioButton24);
        jRadioButton24.setText(" Despesa com Folha de pagamento");
        jPanel1.add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, -1, -1));

        buttonGroup1.add(jRadioButton25);
        jRadioButton25.setText("Impostos");
        jPanel1.add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 690, -1, -1));

        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setText("Despesa com Limpeza");
        jPanel1.add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 710, -1, -1));

        buttonGroup1.add(jRadioButton27);
        jRadioButton27.setText("Material para a manutenção");
        jPanel1.add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 730, -1, -1));

        buttonGroup1.add(jRadioButton28);
        jRadioButton28.setText("Despesas Financeiras");
        jPanel1.add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 750, -1, -1));

        buttonGroup1.add(jRadioButton29);
        jRadioButton29.setText("Despesa com Telefonia");
        jPanel1.add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 770, -1, -1));
        jPanel1.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JDialogNovaCategoria dialog = new JDialogNovaCategoria(new javax.swing.JFrame(), true);
      dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         JDialogNovaCategoria dialog = new JDialogNovaCategoria(new javax.swing.JFrame(), true);
         dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JDialogExcluirCategoria dialog = new JDialogExcluirCategoria(new javax.swing.JFrame(), true);
         dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadastroCategorias dialog = new JDialogCadastroCategorias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
