
package br.iesb.meuprograma.apresentacao;

public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbPerfil = new javax.swing.JComboBox<>();
        btnMostra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiiLogin = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmPortaria = new javax.swing.JMenu();
        jmiCorrespondencia = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmMorador = new javax.swing.JMenu();
        jmiCadastro = new javax.swing.JMenuItem();
        jMenuItemConsultarCadastro = new javax.swing.JMenuItem();
        jmiBiblioteca = new javax.swing.JMenuItem();
        jmiMensagem = new javax.swing.JMenuItem();
        jmiEmitirBoleto = new javax.swing.JMenuItem();
        jmiLocacaoEspaco = new javax.swing.JMenuItem();
        jmiMinhaReserva = new javax.swing.JMenuItem();
        jmAdministracao = new javax.swing.JMenu();
        jmiCriarBoleto = new javax.swing.JMenuItem();
        jmiRelatorio = new javax.swing.JMenuItem();
        jmiContasPagarReceber = new javax.swing.JMenuItem();
        jmiQuadroDeAvisos = new javax.swing.JMenuItem();
        jmiAdmReserva = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiUnidadeAutonoma = new javax.swing.JMenuItem();
        jmiEnxoval = new javax.swing.JMenuItem();
        jmiPlanoDeContas = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GesCon-Sistema de Gestão Condominial");

        jLabel1.setText("Perfil");

        jcbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portaria", "Morador", "Administração", "Sindico" }));

        btnMostra.setText("Habilitar Menu");
        btnMostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraActionPerformed(evt);
            }
        });

        jLabel2.setText("estes itens estão aqui para o desenvolvimento da tela");

        jmArquivo.setText("Arquivo");

        jmiiLogin.setText("Login");
        jmiiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiiLoginActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiiLogin);

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSair);

        jMenuBarPrincipal.add(jmArquivo);

        jmPortaria.setText("Portaria");
        jmPortaria.setEnabled(false);

        jmiCorrespondencia.setText("Correspondencia");
        jmiCorrespondencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCorrespondenciaActionPerformed(evt);
            }
        });
        jmPortaria.add(jmiCorrespondencia);

        jMenu1.setText("Visitantes");

        jMenuItem1.setText("Cadastro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Listagem");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jmPortaria.add(jMenu1);

        jMenuBarPrincipal.add(jmPortaria);

        jmMorador.setText("Morador");
        jmMorador.setEnabled(false);

        jmiCadastro.setText("Cadastro");
        jmiCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroActionPerformed(evt);
            }
        });
        jmMorador.add(jmiCadastro);

        jMenuItemConsultarCadastro.setText("Consultar Cadastro");
        jMenuItemConsultarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarCadastroActionPerformed(evt);
            }
        });
        jmMorador.add(jMenuItemConsultarCadastro);

        jmiBiblioteca.setText("Biblioteca");
        jmMorador.add(jmiBiblioteca);

        jmiMensagem.setText("Mensagem");
        jmMorador.add(jmiMensagem);

        jmiEmitirBoleto.setText("Emitir Boleto");
        jmiEmitirBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmitirBoletoActionPerformed(evt);
            }
        });
        jmMorador.add(jmiEmitirBoleto);

        jmiLocacaoEspaco.setText("Locação de Espaço");
        jmiLocacaoEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLocacaoEspacoActionPerformed(evt);
            }
        });
        jmMorador.add(jmiLocacaoEspaco);

        jmiMinhaReserva.setText("Minha Reserva");
        jmiMinhaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMinhaReservaActionPerformed(evt);
            }
        });
        jmMorador.add(jmiMinhaReserva);

        jMenuBarPrincipal.add(jmMorador);

        jmAdministracao.setText("Administração");
        jmAdministracao.setEnabled(false);

        jmiCriarBoleto.setText("Criar Boleto");
        jmiCriarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCriarBoletoActionPerformed(evt);
            }
        });
        jmAdministracao.add(jmiCriarBoleto);

        jmiRelatorio.setText("Relatórios");
        jmiRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioActionPerformed(evt);
            }
        });
        jmAdministracao.add(jmiRelatorio);

        jmiContasPagarReceber.setText("Contas a Pagar Receber");
        jmiContasPagarReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasPagarReceberActionPerformed(evt);
            }
        });
        jmAdministracao.add(jmiContasPagarReceber);

        jmiQuadroDeAvisos.setText("Quadro de Avisos");
        jmiQuadroDeAvisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuadroDeAvisosActionPerformed(evt);
            }
        });
        jmAdministracao.add(jmiQuadroDeAvisos);

        jmiAdmReserva.setText("Administrar Reserva");
        jmAdministracao.add(jmiAdmReserva);

        jMenuBarPrincipal.add(jmAdministracao);

        jmManutencao.setText("Manutenção");
        jmManutencao.setEnabled(false);

        jmiUnidadeAutonoma.setText("Unidade Autonoma");
        jmiUnidadeAutonoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnidadeAutonomaActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiUnidadeAutonoma);

        jmiEnxoval.setText("Espaço");
        jmiEnxoval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEnxovalActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiEnxoval);

        jmiPlanoDeContas.setText("Plano de Contas");
        jmiPlanoDeContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPlanoDeContasActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiPlanoDeContas);

        jMenuBarPrincipal.add(jmManutencao);

        jMenuAjuda.setMnemonic('j');
        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setMnemonic('S');
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBarPrincipal.add(jMenuAjuda);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnMostra)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        JDialogSobre dialog = new JDialogSobre(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void btnMostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraActionPerformed

        jmMorador.setEnabled(true);
        jmMorador.setEnabled(true);
        jmPortaria.setEnabled(true);
        jmAdministracao.setEnabled(true);
        jmManutencao.setEnabled(true);

        jmMorador.setVisible(false);
        jmMorador.setVisible(false);
        jmPortaria.setVisible(false);
        jmAdministracao.setVisible(false);
        jmManutencao.setVisible(false);

        String X = (String) jcbPerfil.getSelectedItem();
        if ( X == "Portaria") {jmPortaria.setVisible(true);}
        if ( X == "Morador") {jmMorador.setVisible(true);}
        if ( X == "Administração") {jmPortaria.setVisible(true);
            jmAdministracao.setVisible(true);
            jmManutencao.setVisible(true);
        }
        if ( X == "Sindico") {      jmMorador.setVisible(true);
            jmPortaria.setVisible(true);
            jmAdministracao.setVisible(true);
            jmManutencao.setVisible(true);
        }
    }//GEN-LAST:event_btnMostraActionPerformed

    private void jmiiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiiLoginActionPerformed
         JDialogLogin dialog = new JDialogLogin(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiiLoginActionPerformed

    private void jmiLocacaoEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLocacaoEspacoActionPerformed
        JDialogLocacaoEspaco dialog = new JDialogLocacaoEspaco(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiLocacaoEspacoActionPerformed

    private void jmiQuadroDeAvisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuadroDeAvisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiQuadroDeAvisosActionPerformed

    private void jmiPlanoDeContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPlanoDeContasActionPerformed
        JDialogConta dialog = new JDialogConta(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiPlanoDeContasActionPerformed

    private void jmiCorrespondenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCorrespondenciaActionPerformed
     JDialogCorrespondencia dialog = new JDialogCorrespondencia(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiCorrespondenciaActionPerformed

    private void jmiMinhaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMinhaReservaActionPerformed
        JDialogMinhaReserva dialog = new JDialogMinhaReserva(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiMinhaReservaActionPerformed

    private void jmiUnidadeAutonomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnidadeAutonomaActionPerformed
        JDialogUnidade dialog = new JDialogUnidade(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiUnidadeAutonomaActionPerformed

    private void jmiEnxovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEnxovalActionPerformed
       JDialogEspaco dialog = new JDialogEspaco(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiEnxovalActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDialogPortaria_CadastroVisitante cadastroVisita = new JDialogPortaria_CadastroVisitante(new javax.swing.JFrame(), true);
        cadastroVisita.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JDialogPortaria_ListarVisitantes listaVisita = new JDialogPortaria_ListarVisitantes(new javax.swing.JFrame(), true);
        listaVisita.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmiEmitirBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmitirBoletoActionPerformed
        // TODO add your handling code here:
        JDialogMorador_EmitirBoleto moradorBoleto = new JDialogMorador_EmitirBoleto(new javax.swing.JFrame(), true);
        moradorBoleto.setVisible(true);
    }//GEN-LAST:event_jmiEmitirBoletoActionPerformed

    private void jmiCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroActionPerformed
        // TODO add your handling code here:
        JDialogSindico_Cadastro cadastro = new JDialogSindico_Cadastro(new javax.swing.JFrame(), true);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jmiCadastroActionPerformed

    private void jMenuItemConsultarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarCadastroActionPerformed
        // TODO add your handling code here:
        JDialogSindico_EditarCadastro editarCadastro = new JDialogSindico_EditarCadastro(new javax.swing.JFrame(), true);
        editarCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarCadastroActionPerformed

    private void jmiContasPagarReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasPagarReceberActionPerformed
        JDialogAdmContasaPagareReceber dialogo = new JDialogAdmContasaPagareReceber(new javax.swing.JFrame(), true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jmiContasPagarReceberActionPerformed

    private void jmiCriarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCriarBoletoActionPerformed
        JDialogAdmBoletos dialogo = new JDialogAdmBoletos(new javax.swing.JFrame(), true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jmiCriarBoletoActionPerformed

    private void jmiRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioActionPerformed
         JDialogAdmRelatorios dialogo = new JDialogAdmRelatorios(new javax.swing.JFrame(), true);
    dialogo.setVisible(true);  
    }//GEN-LAST:event_jmiRelatorioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemConsultarCadastro;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JComboBox<String> jcbPerfil;
    private javax.swing.JMenu jmAdministracao;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmMorador;
    private javax.swing.JMenu jmPortaria;
    private javax.swing.JMenuItem jmiAdmReserva;
    private javax.swing.JMenuItem jmiBiblioteca;
    private javax.swing.JMenuItem jmiCadastro;
    private javax.swing.JMenuItem jmiContasPagarReceber;
    private javax.swing.JMenuItem jmiCorrespondencia;
    private javax.swing.JMenuItem jmiCriarBoleto;
    private javax.swing.JMenuItem jmiEmitirBoleto;
    private javax.swing.JMenuItem jmiEnxoval;
    private javax.swing.JMenuItem jmiLocacaoEspaco;
    private javax.swing.JMenuItem jmiMensagem;
    private javax.swing.JMenuItem jmiMinhaReserva;
    private javax.swing.JMenuItem jmiPlanoDeContas;
    private javax.swing.JMenuItem jmiQuadroDeAvisos;
    private javax.swing.JMenuItem jmiRelatorio;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiUnidadeAutonoma;
    private javax.swing.JMenuItem jmiiLogin;
    // End of variables declaration//GEN-END:variables
}
